### ISSUE TITLE
Composer source

### ISSUE THREAD

**Issue by paulpach** [pernyblom/pernyblom.github.io#2]
In abundant-music,

the actual composer appears to be in the file [composeworkersource-min.js](https://github.com/pernyblom/pernyblom.github.io/blob/master/abundant-music/js/composeworkersource-min.js)

This file has been minified. So all comments have been removed, and local variables have been mangled.

Can you share the non minified version?

**Comment by nyblomper** [comment]
Added a couple of non-minified source files and a build script
